### ISSUE TITLE
Roadmap to 1.0 release

### ISSUE THREAD

**Issue by anonrig** [socketkit/awacs#1]
## Roadmap

- [x] Add Github CI testing with coveralls support (@anonrig)
- [x] Update Docker image on Dockerhub using Github CI (@anonrig)
- [x] Document kubernetes deployment (@anonrig)
- [x] Move database configuration to Knex.js to make it more configurable for initial setup (@lexor)
- [x] Add Docker compose example (@anonrig)
- [x] Deploy docusaurus to awacs.socketkit.com 
- [x] Automatically deploy Helm Repository
- [x] Improve documentation
- [x] Document private api usage
- [ ] Add OpenAPI specification to docusaurus
- [x] Make Dockerfile lightweight
- [ ] Auto generate client libraries using OpenAPI
- [ ] Add more features for private api
  - [x] Add client endpoints (@anonrig)
  - [x] Add event endpoints (@anonrig)
  - [x] Add session endpoints (@anonrig)
  - [ ] Add application metrics endpoints

**Comment by anonrig** [comment]
At the moment, OpenAPI generator does not support `oneOf` syntax from OpenAPI.
